GameTracker/urls.py
from django.conf.urls import url
from GameTracker import views

app_name = 'GameTracker'

urlpatterns = [
	url(r'^$',views.event_list_view,name='index'),
	# Event patterns
	url(r'^events/$',views.event_list_view,name='event_list'),
	url(r'^events/new/$',views.EventCreateView.as_view(),name='event_new'),
	url(r'^events/delete/(?P<pk>\d+)/$',views.EventDeleteView.as_view(),name='event_delete'),
	url(r'^events/update/(?P<pk>\d+)/$',views.EventUpdateView.as_view(),name='event_update'),
	url(r'^events/(?P<pk>\d+)/$',views.EventDetailView.as_view(),name='event_detail'),
	# Game patterns
	url(r'^games/$',views.game_list_view,name='game_list'),
	url(r'^games/new/$',views.GameCreateView.as_view(),name='game_new'),
	url(r'^games/delete/(?P<pk>\d+)/$',views.GameDeleteView.as_view(),name='game_delete'),
	url(r'^games/update/(?P<pk>\d+)/$',views.GameUpdateView.as_view(),name='game_update'),
	url(r'^games/(?P<pk>\d+)/$',views.GameDetailView.as_view(),name='game_detail'),
	# PlayedGame patterns
	url(r'^playedgame/new/(?P<pk>\d+)/$',views.new_played_game_view,name='played_game_new'),
	url(r'^playedgame/delete/(?P<pk>\d+)/$',views.delete_played_game_view,name='played_game_delete'),
]

OTCGames/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
	url(r'^',include('GameTracker.urls')),
]

GameTracker/models.py
from django.core.urlresolvers import reverse
from django.db import models
from datetime import date, timedelta


class Game(models.Model):
	title = models.CharField(max_length=256, unique=True)
	in_library = models.BooleanField(default=True,verbose_name='In Demo Library')

	def get_absolute_url(self):
		return reverse('GameTracker:game_detail',kwargs={'pk':self.pk})

	def get_played_games(self):
		return PlayedGame.objects.filter(game=self)

	def get_events(self):
		return [item.event for item in self.get_played_games()]

	def get_last_played(self):
		return max([event.date for event in self.get_events()])

	def get_month_plays(self):
		last_month = date.today() - timedelta(days=30)
		return self.get_played_games().filter(event__date__gte=last_month).count()

	def get_year_plays(self):
		last_year = date.today() - timedelta(days=365)
		return self.get_played_games().filter(event__date__gte=last_year).count()

	def get_play_delta(self):
		if len(self.get_events()) > 1:
			dates = [event.date for event in self.get_events()]
			dates.sort()
			deltas = [td.days for td in  [dates[i + 1] - dates[i] for i in range(len(dates)-1)]]
			return round(sum(deltas)/len(deltas))
		else:
			return 0

	def get_year_chart_data(self):
		labels = [year for year in range(2012,date.today().year+1)]
		values = []

		event_years = [event.date.year for event in self.get_events()]

		for year in labels:
			values.append(event_years.count(year))

		return {'labels':labels,'values':values}

	def get_month_chart_data(self):
		labels = []
		for year in range(2012,date.today().year+1):
			for m in ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec']:
				labels.append(str(m + " " + str(year)))

		all_months = []
		for year in range(2012,date.today().year+1):
			for i in range(1,13):
				all_months.append((year,i))

		event_months = [(event.date.year,event.date.month) for event in self.get_events()]

		values = []
		for month in all_months:
			values.append(event_months.count(month))

		return {'labels':labels,'values':values}

	def __str__(self):
		return self.title

	class Meta:
		ordering = ['title']


class Event(models.Model):
	date = models.DateField(unique=True)
	player_count = models.PositiveSmallIntegerField(verbose_name='Number of Participants')
	games = models.ManyToManyField(Game, through='PlayedGame')

	def get_absolute_url(self):
		return reverse('GameTracker:event_detail',kwargs={'pk':self.pk})

	def get_played_games(self):
		return PlayedGame.objects.filter(event=self)

	def get_game_count(self):
		return games.count()

	def __str__(self):
		return self.date.strftime('%Y-%m-%d')

	class Meta:
		ordering = ['-date']


class PlayedGame(models.Model):
	event = models.ForeignKey(Event, on_delete=models.CASCADE)
	game = models.ForeignKey(Game, on_delete=models.CASCADE)
	game_player_count = models.PositiveSmallIntegerField()

	def __str__(self):
		return str(self.event) + " | " + str(self.game)

	class Meta:
		unique_together = ('event','game')
		ordering = ['event','game']

GameTracker/forms.py
from django import forms
from GameTracker.models import Event,Game,PlayedGame


class DateInput(forms.DateInput):
	input_type = 'date'


class EventForm(forms.ModelForm):

	class Meta():
		model = Event
		fields = ('date','player_count')

		widgets = {
			'date':DateInput(attrs={'class':'form-control'}),
			'player_count':forms.NumberInput(attrs={'class':'form-control'})
		}


class GameForm(forms.ModelForm):

	class Meta():
		model = Game
		fields = ('title','in_library')

		widgets = {
			'title':forms.TextInput(attrs={'class':'form-control'}),
			'in_library':forms.CheckboxInput()
		}


class NewPlayedGameForm(forms.ModelForm):

	class Meta():
		model = PlayedGame
		fields = ['game','game_player_count']

		widgets = {
			'game':forms.Select(attrs={'class':'form-control'}),
			'game_player_count':forms.NumberInput(attrs={'class':'form-control'})
		}

GameTracker/views.py
import re
from django.core.urlresolvers import reverse_lazy
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render,redirect,get_object_or_404
from django.views.generic import View,TemplateView,ListView,DetailView,CreateView,DeleteView,UpdateView
from GameTracker.models import Game,Event,PlayedGame
from GameTracker.forms import EventForm,GameForm,NewPlayedGameForm


# Event views

class EventCreateView(CreateView):
	model = Event
	form_class = EventForm


class EventDeleteView(DeleteView):
	model = Event
	success_url = reverse_lazy('GameTracker:event_list')


class EventUpdateView(UpdateView):
	model = Event
	form_class = EventForm


class EventDetailView(DetailView):
	model = Event

	# Need in include form for adding played games to the event
	def get(self, request, *args, **kwargs):
		self.object = self.get_object()
		played_game_form = NewPlayedGameForm(self.request.GET or None)
		context = self.get_context_data(**kwargs)
		context['played_game_form'] = played_game_form
		return self.render_to_response(context)


def event_list_view(request):
	event_list = Event.objects.all()
	paginator = Paginator(event_list, 10)
	page = request.GET.get('page')

	try:
		events = paginator.page(page)
		page = int(page)
		if paginator.num_pages > 10:
			if page <= 6:
				nav_list = list(range(1,11))
			elif paginator.num_pages - page < 6:
				nav_list = list(range(paginator.num_pages-10,paginator.num_pages+1))
			else:
				nav_list = list(range(page-5,page+6))
		else:
			nav_list = list(range(1,paginator.num_pages+1))
	except PageNotAnInteger:
		# If page is not an integer, deliver first page.
		return redirect('/events/?page=1')
	except EmptyPage:
		# If page is out of range (e.g. 9999), deliver last page of results.
		return redirect('/events/?page=' + str(paginator.num_pages))

	return render(request, 'GameTracker/event_list.html', {'events': events,'nav_list':nav_list})


# Game Views

class GameCreateView(CreateView):
	model = Game
	form_class = GameForm


class GameDeleteView(DeleteView):
	model = Game
	success_url = reverse_lazy('GameTracker:game_list')


class GameUpdateView(UpdateView):
	model = Game
	form_class = GameForm


class GameDetailView(DetailView):
	model = Game


def game_list_view(request):
	category = request.GET.get('category')

	try:
		pattern = re.compile("^[a-zA-Z]$")
		if category == 'other':
			games = Game.objects.exclude(title__regex=r'^[a-zA-Z]')
		elif pattern.match(category):
			games = Game.objects.filter(title__istartswith=category)
		else:
			games = Game.objects.all()
			category = 'all'
	except:
		games = Game.objects.all()
		category = 'all'

	return render(request, 'GameTracker/game_list.html', {'games': games,'category':category})


# PlayedGame Views

def new_played_game_view(request,pk):
	event = get_object_or_404(Event,pk=pk)
	form = NewPlayedGameForm(request.POST)

	if form.is_valid():
		played_game = form.save(commit=False)
		played_game.event = event
		played_game.save()

	return redirect('/events/' + str(pk))


def delete_played_game_view(request,pk):
	pg_instance = get_object_or_404(PlayedGame,pk=pk)
	event_pk = pg_instance.event.pk
	pg_instance.delete()

	return redirect('/events/' + str(event_pk))

templates/GameTracker/event_confirm_delete.html
{% extends 'base.html' %}

{% block head_block %}
	<title>Game Tracker | Delete Event</title>
{% endblock %}

{% block body_block %}
	<h1>Are you sure you want to delete the following event?</h1>

	<div class="panel panel-primary fit-content">
		<div class="panel-heading">
			<h2 class="panel-title">Event Details</h2>
		</div>

		<div class="panel-body">
			<h2>{{object.date|date:'l F jS, Y'}}</h2>
			<p>{{event.player_count}} Participants | {{event.games.count}} Games Played</p>
		</div>
	</div>

	<div class="alert alert-warning fit-content">
		<p>
			Deleting this event will delete all game play instances for this event as well.
			<br>
			The play history trend charts for all associated games will no longer include this event.
		</p>
	</div>

	<form method="post">
		{% csrf_token %}
		<button type="submit" class="btn btn-danger">Confirm Event Deletion</button>
		<a class="btn btn-default" href="{% url 'GameTracker:event_detail' pk=object.pk %}">Cancel</a>
	</form>
{% endblock %}

templates/GameTracker/event_detail.html
{% extends 'base.html' %}

{% block head_block %}
	<title>Game Tracker | Event Details</title>
{% endblock %}

{% block body_block %}
	<h2>{{object.date|date:'l F jS, Y'}}</h2>

	<div class="">
		<table class="table borderless">
			<tr>
				<td><span class="h4">{{object.player_count}} Participants | {{object.games.count}} Games Played</span></td>
				<td align="right">
					<a class="btn btn-primary" href="{% url 'GameTracker:event_update' pk=object.pk %}">Edit Event</a>
					<a class="btn btn-default" href="{% url 'GameTracker:event_delete' pk=object.pk %}">Delete Event</a>
				</td>
			</tr>
		</table>
	</div>

	<div class="panel panel-primary">
		<div class="panel-heading">
			<h3 class="panel-title">Games Played</h3>
		</div>
		<table class="table">
			<tr>
				<th>Game Title</th>
				<th class="text-center">Number of Players</th>
				<th class="text-center">Action</th>
			</tr>
			{% if object.games.count != 0 %}
				{% for pg in object.get_played_games %}
				<tr>
					<td><span class="h4"><a href="{% url 'GameTracker:game_detail' pk=pg.game.pk %}">{{pg.game.title}}</a></span></td>
					<td class="text-center"><span class="h4">{{pg.game_player_count}}</span></td>
					<td class="text-center"><a class="btn btn-xs btn-danger" href="{% url 'GameTracker:played_game_delete' pk=pg.pk %}">Delete</a></td>
				</tr>
				{% endfor %}
			{% endif %}
			<tr>
				<form action="{% url 'GameTracker:played_game_new' pk=object.pk %}" method="POST">
					{% csrf_token %}
					<td>{{played_game_form.game}}</td>
					<td class="text-center">{{played_game_form.game_player_count}}</td>
					<td class="text-center"><button type="submit" class="btn btn-success">Add Game</button></td>
				</form>
			</tr>
		</table>
	</div>
{% endblock %}

templates/GameTracker/event_form.html
{% extends 'base.html' %}

{% block head_block %}
	{% if not form.instance.pk %}
		<title>Game Tracker | New Event</title>
	{% else %}
		<title>Game Tracker | Edit Event</title>
	{% endif %}
{% endblock %}

{% block body_block %}
	<div class="panel panel-primary fit-content">
		<div class="panel-heading">
			{% if not form.instance.pk %}
				<h2 class="panel-title">New Game Night Event</h2>
			{% else %}
				<h2 class="panel-title">Edit Event Details</h2>
			{% endif %}
		</div>

		{% if not form.instance.pk %}
			<div class="panel-body">
				<div class="alert alert-info">
					<p>Start by creating a game night event, then add games in the next step.</p>
				</div>
			</div>
		{% endif %}

		<form method="post">
			{% csrf_token %}
			<table class="table">
				{{form.as_table}}
				<tr><th></th><td></td></tr>
			</table>
				{% if not form.instance.pk %}
					<button type="submit" class="btn btn-primary form-btn">Create Event</button>
					<a href="{% url 'GameTracker:event_list' %}" class="btn btn-default form-btn">Cancel</a>
				{% else %}
					<button type="submit" class="btn btn-primary form-btn">Update Event</button>
					<a href="{% url 'GameTracker:event_detail' pk=form.instance.pk %}" class="btn btn-default form-btn">Cancel</a>
				{% endif %}
		</form>
	</div>
{% endblock %}

templates/GameTracker/event_list.html
{% extends 'base.html' %}

{% block head_block %}
	<title>Game Tracker | Events</title>
{% endblock %}

{% block body_block %}
	<span class="h1">Game Night Events</span>
	<br />
	<a class="btn btn-xs btn-primary" href="{% url 'GameTracker:event_new' %}">Add New Event</a>

	{% if not events %}
		<div class="alert alert-info fit-content">
			<h3>Unfortunately, there are no events to display. Please create a new event.</h3>
		</div>
	{% else %}
		<nav aria-label="...">
			<ul class="pagination">
				<li class="page-item"><a class="page-link" href="?page=1">First</a></li>
				{% if events.has_previous %}
					<li class="page-item"><a class="page-link" href="?page={{ events.previous_page_number }}">Previous</a></li>
				{% else %}
					<li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
				{% endif %}

				{% if nav_list|first > 1 %}
					<li class="page-item disabled"><span>...</span></li>
				{% endif %}

				{% for page_num in nav_list %}
					{% if page_num == events.number %}
						<li class="page-item active"><a class="page-link" href="?page={{page_num}}">{{page_num}}<span class="sr-only">(current)</a></li>
					{% else %}
						<li class="page-item"><a class="page-link" href="?page={{page_num}}">{{page_num}}</a></li>
					{% endif %}
				{% endfor %}

				{% if nav_list|last < events.paginator.num_pages %}
					<li class="page-item disabled"><span>...</span></li>
				{% endif %}

				{% if events.has_next %}
					<li class="page-item"><a class="page-link" href="?page={{ events.next_page_number }}">Next</a></li>
				{% else %}
					<li class="page-item disabled"><a class="page-link" href="#">Next</a></li>
				{% endif %}
				<li class="page-item"><a class="page-link" href="?page={{ events.paginator.num_pages }}">Last</a></li>
			</ul>
		</nav>

		{% for event in events %}
			<div class="event-title-block">
				<p>
					<a href="{% url 'GameTracker:event_detail' pk=event.pk %}"><span class="h3">{{event.date|date:'l F jS, Y'}}</span></a>
					<br />
					<span class="h4">{{event.player_count}} Participants | {{event.games.count}} Games Played</span>
				</p>
			</div>
		{% endfor %}
	{% endif %}
{% endblock %}

templates/GameTracker/game_confirm_delete.html
{% extends 'base.html' %}

{% block head_block %}
	<title>Game Tracker | Delete Game</title>
{% endblock %}

{% block body_block %}
	<h1>Are you sure you want to delete the following game?</h1>

	<div class="panel panel-primary fit-content">
		<div class="panel-heading">
			<h2 class="panel-title">Game Details</h2>
		</div>

		<div class="panel-body">
			<h2>{{object.title}}</h2>
			{% if object.in_library %}
				<p>In Demo Library: Yes</p>
			{% else %}
				<p>In Demo Library: No</p>
			{% endif %}
		</div>
	</div>

	<div class="alert alert-warning fit-content">
		<p>
			Deleting this game will delete all game play instances associated to events as well.
		</p>
	</div>

	<form method="post">
		{% csrf_token %}
		<button type="submit" class="btn btn-danger">Confirm Game Deletion</button>
		<a class="btn btn-default" href="{% url 'GameTracker:game_detail' pk=object.pk %}">Cancel</a>
	</form>
{% endblock %}

templates/GameTracker/game_detail.html
{% extends 'base.html' %}

{% block head_block %}
	<title>Game Tracker | Game Details</title>
	<script type="text/javascript">
		window.onload = function(){
			Chart.defaults.global.defaultFontSize = 16;
			var ctx = document.getElementById('yearlyTrendChart');
			var yearlyChart = new Chart(ctx, {
				type: 'bar',
				data: {
					labels: [
						{% for label in object.get_year_chart_data.labels %}
							'{{label}}',
						{% endfor %}
					],
					datasets: [{
						data: [
							{% for value in object.get_year_chart_data.values %}
								{{value}},
							{% endfor %}
						],
						borderWidth: 1,
						backgroundColor: "#bce8f1",
		    			borderColor: "#31708f",
						hoverBackgroundColor: "#bce8f1",
		    			hoverBorderColor: "#31708f",
					}]
				},
				options: {
					responsive: true,
					aspectRatio: 3,
					legend: {
						display: false,
					},
					scales: {
            			yAxes: [{
                			ticks: {
                    			beginAtZero: true
                			}
            			}]
        			},
					layout: {
			            padding: {
			                left: 0,
			                right: 0,
			                top: 20,
			                bottom: 0
			            }
		        	}
				},
			});

			var ctx = document.getElementById('monthlyTrendChart');
			var monthlyChart = new Chart(ctx, {
				type: 'bar',
				data: {
					labels: [
						{% for label in object.get_month_chart_data.labels %}
							'{{label}}',
						{% endfor %}
					],
					datasets: [{
						data: [
							{% for value in object.get_month_chart_data.values %}
								{{value}},
							{% endfor %}
						],
						borderWidth: 1,
						backgroundColor: "#bce8f1",
		    			borderColor: "#31708f",
						hoverBackgroundColor: "#bce8f1",
		    			hoverBorderColor: "#31708f",
					}]
				},
				options: {
					responsive: true,
					aspectRatio: 3,
					legend: {
						display: false,
					},
					scales: {
            			yAxes: [{
                			ticks: {
                    			beginAtZero: true
                			}
            			}],
        			},
					layout: {
			            padding: {
			                left: 0,
			                right: 0,
			                top: 20,
			                bottom: 0
			            }
		        	}
				},
			});
		}
	</script>
{% endblock %}

{% block body_block %}
	<table class="table borderless">
		<tr>
			<td><span class="h2">{{ object.title }}</span></td>
			<td align="right">
				<a class="btn btn-primary" href="{% url 'GameTracker:game_update' pk=object.pk %}">Edit Game</a>
				<a class="btn btn-default" href="{% url 'GameTracker:game_delete' pk=object.pk %}">Delete Game</a>
			</td>
		</tr>
	</table>

	{% if object.get_played_games.count == 0 %}
		{% if object.in_library %}
			<p>In Demo Library: Yes</p>
		{% else %}
			<p>In Demo Library: No</p>
		{% endif %}
		<div class="alert alert-info fit-content">
			<p>
				This game has not been added to any events.
				<br>
				Add this game to an event to see gameplay data.
			</p>
		</div>
	{% else %}
		<div class="panel panel-primary">
			<div class="panel-heading">
				<h3 class="panel-title">Basic Information</h3>
			</div>

			<table class="table">
				<tr>
					<th class="text-center">Most Recent Play</th>
					<th class="text-center">Avg. Play Frequency</th>
					<th class="text-center">Plays in Last 30 Days</th>
					<th class="text-center">Plays in Last Year</th>
					<th class="text-center">Lifetime Plays</th>
					<th class="text-center">In Library?</th>
				</tr>
				<tr>
					<td class="text-center">{{object.get_last_played|date:'F j, Y'}}</td>
					<td class="text-center">{{object.get_play_delta}} days</td>
					<td class="text-center">{{object.get_month_plays}}</td>
					<td class="text-center">{{object.get_year_plays}}</td>
					<td class="text-center">{{object.get_events|length}}</td>
					<td class="text-center">
						{% if object.in_library %}
							Yes
						{% else %}
							No
						{% endif %}
					</td>
				</tr>
			</table>
		</div>

		<div class="panel panel-primary">
			<div class="panel-heading">
				<span class="panel-title">Play History&nbsp;</span>
				<a href="#eventList" class="btn btn-xs btn-default" data-toggle="collapse" aria-expanded="true">Toggle</a>
			</div>

			<div class="list-group collapse" id="eventList">
				{% for event in object.get_events %}
					<a class="list-group-item" href="{% url 'GameTracker:event_detail' pk=event.pk %}">{{ event.date|date:'l F jS, Y' }}</a>
				{% endfor %}
			</div>
		</div>

		<div class="panel panel-primary">
			<div class="panel-heading">
				<span class="panel-title">Plays by Year</span>
			</div>

			<canvas id="yearlyTrendChart"></canvas>
		</div>

		<div class="panel panel-primary">
			<div class="panel-heading">
				<span class="panel-title">Plays by Month</span>
			</div>

			<canvas id="monthlyTrendChart"></canvas>
		</div>
	{% endif %}
{% endblock %}

templates/GameTracker/game_form.html
{% extends 'base.html' %}

{% block head_block %}
	{% if not form.instance.pk %}
		<title>Game Tracker | New Game</title>
	{% else %}
		<title>Game Tracker | Edit Game</title>
	{% endif %}
{% endblock %}

{% block body_block %}
	<div class="panel panel-primary fit-content">
		<div class="panel-heading">
			{% if not form.instance.pk %}
				<h2 class="panel-title">New Game</h2>
			{% else %}
				<h2 class="panel-title">Edit Game Details</h2>
			{% endif %}
		</div>

		{% if not form.instance.pk %}
			<div class="panel-body">
				<div class="alert alert-info">
					<p>
						Create a new game here, then edit an event to add games to it.
					</p>
				</div>
			</div>
		{% endif %}

		<form method="post">
			{% csrf_token %}
			<table class="table">
				{{form.as_table}}
				<tr><th></th><td></td></tr>
			</table>

			{% if not form.instance.pk %}
				<button type="submit" class="btn btn-primary form-btn">Create Game</button>
				<a href="{% url 'GameTracker:game_list' %}" class="btn btn-default form-btn">Cancel</a>
			{% else %}
				<button type="submit" class="btn btn-primary form-btn">Update Game</button>
				<a href="{% url 'GameTracker:game_detail' pk=form.instance.pk %}" class="btn btn-default form-btn">Cancel</a>
			{% endif %}

		</form>
	</div>
{% endblock %}

templates/GameTracker/game_list.html
{% extends 'base.html' %}

{% block head_block %}
	<title>Game Tracker | Games</title>
{% endblock %}

{% block body_block %}
	<span class="h1">Game List</span>
	<br />
	<a class="btn btn-xs btn-primary" href="{% url 'GameTracker:game_new' %}">Add New Game</a>

	<nav>
		<ul class="pagination">
			{% if category|upper == 'ALL' %}
				<li class="active"><a href="#">All</a></li>
			{% else %}
				<li><a href="/games">All</a></li>
			{% endif %}

			{% if category|upper == 'OTHER' %}
				<li class="active"><a href="#">#</a></li>
			{% else %}
				<li><a href="?category=other">#</a></li>
			{% endif %}

			{% for letter in 'ABCDEFGHIJKLMNOPQRSTUVWXYZ' %}
				{% if category|upper == letter %}
					<li class="active"><a href="#">{{letter}}</a></li>
				{% else %}
					<li><a href="?category={{letter}}">{{letter}}</a></li>
				{% endif %}
			{% endfor %}
		</ul>
	</nav>

	{% if not games %}
		<div class="alert alert-info fit-content">
			<span class="h3">
				Unfortunately, there are no games to display for this category.
				<br>
				Please choose another category or create a new game.
			</span>
		</div>
	{% else %}
		<div class="fit-content">
			<table class="table borderless">
				{% for game in games %}
					{% if forloop.first %}<tr>{% endif %}
					<td class="h4 padded-right"><a href="{% url 'GameTracker:game_detail' pk=game.pk %}">{{ game.title }}</a></td>
					{% if forloop.counter|divisibleby:3 %}</tr><tr>{% endif %}
					{% if forloop.last %}</tr>{% endif %}
				{% endfor %}
			</table>
		</div>
	{% endif %}
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
	<head>
		<meta charset="utf-8">
		<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
		<link rel="stylesheet" href="{% static 'css/GameTracker.css' %}">
		<script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/chart.js' %}"></script>
		{% block head_block %}
		{% endblock %}
	</head>
	<body>
		<nav class="navbar navbar-default navbar-inverse navbar-fixed-top custom-font">
			<div class="container">
				<div class="navbar-header">
					<a href="{% url 'GameTracker:index' %}" class="navbar-brand">Game Tracker</a>
				</div>

				<ul class="nav navbar-nav">
					<li><a href="{% url 'GameTracker:event_list' %}">Events</a></li>
					<li><a href="{% url 'GameTracker:game_list' %}">Games</a></li>
					<li><a href="{% url 'GameTracker:event_new' %}">New Event</a></li>
					<li><a href="{% url 'GameTracker:game_new' %}">New Game</a></li>
				</ul>
			</div>
	    </nav>
		<div class="container">
			<div id="BodySpacer">&nbsp;</div>
			{% block body_block %}
			{% endblock %}
		</div>
	</body>
</html>